#!/usr/bin/env python3
"""Export the Nexum Graph spec and whitepaper `.docx` files to Markdown."""

from __future__ import annotations

import argparse
import textwrap
import xml.etree.ElementTree as ET
import zipfile
from dataclasses import dataclass
from pathlib import Path

NS = {"w": "http://schemas.openxmlformats.org/wordprocessingml/2006/main"}

DOCUMENTS = {
    "spec": {
        "source": "Nexum_Graph_Final_Implementation_Spec.docx",
        "target": "docs/Nexum_Graph_Final_Implementation_Spec.md",
    },
    "whitepaper-v1": {
        "source": "Nexum_Graph_Whitepaper_v1.docx",
        "target": "docs/Nexum_Graph_Whitepaper_v1.md",
    },
    "whitepaper-v3": {
        "source": "Nexum_Graph_Whitepaper_v3.docx",
        "target": "docs/Nexum_Graph_Whitepaper_v3.md",
    },
}


@dataclass(frozen=True)
class Paragraph:
    text: str
    style: str
    is_list: bool


def repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def source_path(doc_key: str) -> Path:
    return repo_root() / DOCUMENTS[doc_key]["source"]


def target_path(doc_key: str) -> Path:
    return repo_root() / DOCUMENTS[doc_key]["target"]


def extract_paragraphs(path: Path) -> list[Paragraph]:
    with zipfile.ZipFile(path) as archive:
        root = ET.fromstring(archive.read("word/document.xml"))

    paragraphs: list[Paragraph] = []
    for paragraph in root.findall(".//w:p", NS):
        runs = [node.text or "" for node in paragraph.findall(".//w:t", NS)]
        text = "".join(runs).strip()
        if not text:
            continue

        style = paragraph.find("./w:pPr/w:pStyle", NS)
        style_name = style.attrib.get(f"{{{NS['w']}}}val", "") if style is not None else ""
        is_list = paragraph.find("./w:pPr/w:numPr", NS) is not None
        paragraphs.append(Paragraph(text=text, style=style_name, is_list=is_list))

    return paragraphs


def heading_prefix(style: str) -> str | None:
    mapping = {
        "Title": "#",
        "Heading1": "##",
        "Heading2": "###",
        "Heading3": "####",
        "Heading4": "#####",
    }
    return mapping.get(style)


def fence_language(text: str) -> str:
    first_line = text.lstrip().splitlines()[0] if text.strip() else ""
    if "[workspace]" in first_line or "pub struct" in first_line or "fn " in first_line:
        return "rust"
    if first_line.startswith("cargo ") or first_line.startswith("git "):
        return "bash"
    if first_line.startswith("nex "):
        return "bash"
    return ""


def looks_like_code(text: str) -> bool:
    if "\n" in text:
        return True
    code_markers = (
        "pub struct",
        "pub enum",
        "pub trait",
        "impl ",
        "fn ",
        "#[derive",
        "[workspace]",
        "cargo ",
        "git ",
        "nex ",
        "codex ",
        "```",
    )
    return any(marker in text for marker in code_markers)


def render_markdown(doc_key: str, paragraphs: list[Paragraph]) -> str:
    source = DOCUMENTS[doc_key]["source"]
    lines = [
        "<!-- Generated by tools/export_spec_markdown.py from "
        f"{source}. Prefer editing the Markdown file only for minor copy fixes; "
        "the .docx remains the archival source. -->",
        "",
    ]

    in_list = False
    in_code = False

    for paragraph in paragraphs:
        prefix = heading_prefix(paragraph.style)
        if prefix is not None:
            if in_code:
                lines.extend(["```", ""])
                in_code = False
            if in_list:
                lines.append("")
                in_list = False
            lines.extend([f"{prefix} {paragraph.text}", ""])
            continue

        if paragraph.is_list or paragraph.style == "ListParagraph":
            if in_code:
                lines.extend(["```", ""])
                in_code = False
            lines.append(f"- {paragraph.text}")
            in_list = True
            continue

        if in_list:
            lines.append("")
            in_list = False

        if looks_like_code(paragraph.text):
            if not in_code:
                lines.extend([f"```{fence_language(paragraph.text)}".rstrip(), paragraph.text])
                in_code = True
            else:
                lines.append(paragraph.text)
            continue

        if in_code:
            lines.extend(["```", ""])
            in_code = False

        wrapped = textwrap.wrap(paragraph.text, width=100, break_long_words=False)
        if wrapped:
            lines.extend(wrapped)
            lines.append("")

    if in_code:
        lines.extend(["```", ""])

    return "\n".join(lines).rstrip() + "\n"


def export_document(doc_key: str) -> Path:
    paragraphs = extract_paragraphs(source_path(doc_key))
    markdown = render_markdown(doc_key, paragraphs)
    output = target_path(doc_key)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(markdown, encoding="utf-8")
    return output


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--doc",
        choices=["all", *DOCUMENTS.keys()],
        default="all",
        help="Document to export. Defaults to all tracked docx sources.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    doc_keys = list(DOCUMENTS) if args.doc == "all" else [args.doc]
    for doc_key in doc_keys:
        output = export_document(doc_key)
        print(output.relative_to(repo_root()))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
